### PR TITLE
Update gatsby-config.js

### LINKED ISSUE #26: Add RSS feed for meetups | Ajout d'un flux RSS pour les meetups
🇺🇸 

# Add RSS feed for meetups

This feature is a nice to have, but it could be awesome to have a RSS feed for the meetups as they are published like blog post.

As we are using Gatsby, the [`gatsby-plugin-feed`](https://www.gatsbyjs.com/plugins/gatsby-plugin-feed/) plugin can be useful to create the feed.

🇫🇷 

# Ajout d'un flux RSS pour les meetups

Ca pourrait être sympa d'avoir les annonces de meetup dans un flux RSS, il y a encore des gens qui les utilisent (eh oui) ou encore, qui préfèrent ce moyen plutôt que de s'inscrire sur meetup.com ou de donner leurs adresses emails pour s'avoir quand un meetup aura lieu.

Comme nous utilisons Gatsby, le plugin [`gatsby-plugin-feed`](https://www.gatsbyjs.com/plugins/gatsby-plugin-feed/) peut être utile pour créer le flux.

### PR DESCRIPTION
**Pull request by tacoelho**
Add RSS feed for meetups | Ajout d'un flux RSS pour les meetups #26

Closes #26

### CODE REVIEW

**Comment by yoannfleurydev** [comment]
Hi, thanks a lot for the PR. The build is currently failing as the plugin is not in the `package.json`

```
11:54:12 PM: $ gatsby build
11:54:15 PM: error Couldn't find the "gatsby-plugin-feed" plugin declared in "/opt/build/repo/gatsby-config.js".
11:54:15 PM: Tried looking for a local plugin in /opt/build/repo/plugins/gatsby-plugin-feed.
11:54:15 PM: Tried looking for an installed package in the following paths:
11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/dist/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /opt/build/repo/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /opt/build/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /opt/node_modules/gatsby-plugin-feed
11:54:15 PM:  - /node_modules/gatsby-plugin-feed
11:54:15 PM: not finished open and validate gatsby-configs - 0.032s
```

**Comment by tacoelho** [comment]
> Hi, thanks a lot for the PR. The build is currently failing as the plugin is not in the `package.json`
> 
> ```
> 11:54:12 PM: $ gatsby build
> 11:54:15 PM: error Couldn't find the "gatsby-plugin-feed" plugin declared in "/opt/build/repo/gatsby-config.js".
> 11:54:15 PM: Tried looking for a local plugin in /opt/build/repo/plugins/gatsby-plugin-feed.
> 11:54:15 PM: Tried looking for an installed package in the following paths:
> 11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/dist/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /opt/build/repo/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /opt/build/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /opt/node_modules/gatsby-plugin-feed
> 11:54:15 PM:  - /node_modules/gatsby-plugin-feed
> 11:54:15 PM: not finished open and validate gatsby-configs - 0.032s
> ```

Added :)

**Comment by yoannfleurydev** [comment]
The provided version `2.24.84` for `gatsby-plugin-feed` does not exist, so the build is still failing:

```
4:57:49 PM: yarn install v1.17.0
4:57:49 PM: [1/4] Resolving packages...
4:57:50 PM: error Couldn't find any versions for "gatsby-plugin-feed" that matches "2.24.84"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
4:57:50 PM: Error during Yarn install
4:57:50 PM: Build was terminated: Build script returned non-zero exit code: 1
4:57:50 PM: Failing build: Failed to build site
4:57:50 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
4:57:50 PM: Finished processing build request in 36.351055019s
```

As I can see on npmjs.org, the latest version seems to be the [`2.5.18`](https://www.npmjs.com/package/gatsby-plugin-feed)

**Comment by tacoelho** [comment]
> The provided version `2.24.84` for `gatsby-plugin-feed` does not exist, so the build is still failing:
> 
> ```
> 4:57:49 PM: yarn install v1.17.0
> 4:57:49 PM: [1/4] Resolving packages...
> 4:57:50 PM: error Couldn't find any versions for "gatsby-plugin-feed" that matches "2.24.84"
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 4:57:50 PM: Error during Yarn install
> 4:57:50 PM: Build was terminated: Build script returned non-zero exit code: 1
> 4:57:50 PM: Failing build: Failed to build site
> 4:57:50 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
> 4:57:50 PM: Finished processing build request in 36.351055019s
> ```
> 
> As I can see on npmjs.org, the latest version seems to be the [`2.5.18`](https://www.npmjs.com/package/gatsby-plugin-feed)

updated.

**Comment by tacoelho** [comment]
> > The provided version `2.24.84` for `gatsby-plugin-feed` does not exist, so the build is still failing:
> > ```
> > 4:57:49 PM: yarn install v1.17.0
> > 4:57:49 PM: [1/4] Resolving packages...
> > 4:57:50 PM: error Couldn't find any versions for "gatsby-plugin-feed" that matches "2.24.84"
> > info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> > 4:57:50 PM: Error during Yarn install
> > 4:57:50 PM: Build was terminated: Build script returned non-zero exit code: 1
> > 4:57:50 PM: Failing build: Failed to build site
> > 4:57:50 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
> > 4:57:50 PM: Finished processing build request in 36.351055019s
> > ```
> > 
> > 
> > As I can see on npmjs.org, the latest version seems to be the [`2.5.18`](https://www.npmjs.com/package/gatsby-plugin-feed)
> 
> updated.

It´s actually 2.5.19 and it didn´t work.

**Comment by yoannfleurydev** [comment]
Thanks for you time, I fixed the latest issues so I can merge it now.

**Pull request merged**
